const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=1200,H=720; const imgCache={};
const assets={ground:'assets/environment/ground.png',base:'assets/environment/base_castle.png',tree:'assets/environment/tree_large.png',bush:'assets/environment/bush_large.png',rock:'assets/environment/rock.png',camp:'assets/environment/campfire.png',chest:'assets/environment/chest.png',archer:'assets/towers/archer.png',cannon:'assets/towers/cannon.png',mage:'assets/towers/mage.png'};
for(let i=1;i<=10;i++)assets['e'+i]=`assets/enemies/e${i}.png`;
// The supplied asset pack has no e4.png; use an existing enemy sprite as a safe fallback.
if(!assets.e4) assets.e4=assets.e3;
for(const [k,p] of Object.entries(assets)){const im=new Image();im.src=p;imgCache[k]=im}
const snd={}; const soundFiles={ui:'assets/audio/ui_click.wav',turret:'assets/audio/turret.wav',rocket:'assets/audio/rocket.wav',reward:'assets/audio/reward.wav',death:'assets/audio/death.wav',boss:'assets/audio/boss.wav'}; for(const n of Object.keys(soundFiles)){const a=new Audio(soundFiles[n]);a.preload='auto';snd[n]=a}
function play(n,v=.22){try{snd[n].currentTime=0;snd[n].volume=v;snd[n].play().catch(()=>{})}catch(e){}}
const path=[{x:-50,y:150},{x:210,y:150},{x:210,y:330},{x:440,y:330},{x:440,y:125},{x:690,y:125},{x:690,y:350},{x:950,y:350},{x:950,y:175},{x:1250,y:175}];
const pads=[{x:110,y:285},{x:320,y:185},{x:320,y:430},{x:555,y:250},{x:805,y:225},{x:805,y:450},{x:1040,y:285},{x:1040,y:500},{x:550,y:510},{x:290,y:570}];
let towers=[],enemies=[],shots=[],fx=[],wave=0,lives=20,gold=300,score=0,running=false,selected='archer',selectedTower=null,hero=null,spawnTimer=0,spawnLeft=0,waveTimer=0,gameEnded=false;
const towerCfg={archer:{name:'Watchtower',cost:75,dmg:17,range:165,rate:650,color:'#f4c95d'},cannon:{name:'Guard Tower',cost:125,dmg:38,range:145,rate:1100,color:'#e88b54'},mage:{name:'Magic Stone',cost:175,dmg:28,range:185,rate:800,color:'#76b9ff'}};
function loadScores(){let s=JSON.parse(localStorage.getItem('irwflix_defense_scores')||'[]');s.sort((a,b)=>b.score-a.score);document.getElementById('scores').innerHTML=s.slice(0,10).map((x,i)=>`<li><b>${i+1}. ${x.name}</b> — ${x.score.toLocaleString()} <small>Wave ${x.wave}</small></li>`).join('')||'<li>No runs registered yet.</li>'}
function saveScore(){let name=prompt('Enter your name for the leaderboard:','Player')||'Player';let s=JSON.parse(localStorage.getItem('irwflix_defense_scores')||'[]');s.push({name,score,wave,date:Date.now()});s.sort((a,b)=>b.score-a.score);s=s.slice(0,10);localStorage.setItem('irwflix_defense_scores',JSON.stringify(s));loadScores();document.getElementById('resultStatus').textContent='Score registered in the Top 10 list.';document.getElementById('submitResult').disabled=true}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1500)}
function setStats(){waveEl.textContent=`${wave}/20`;lifeEl.textContent=lives;goldEl.textContent=gold;scoreEl.textContent=score}
const waveEl=document.getElementById('wave'),lifeEl=document.getElementById('lives'),goldEl=document.getElementById('gold'),scoreEl=document.getElementById('score');
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
const segmentLengths=[]; let totalPath=0; for(let i=0;i<path.length-1;i++){const len=dist(path[i],path[i+1]);segmentLengths.push(len); totalPath+=len;}
function pathPoint(distanceAlong){let remaining=Math.max(0,Math.min(distanceAlong,totalPath));for(let i=0;i<path.length-1;i++){const len=segmentLengths[i];if(remaining<=len){const a=path[i],b=path[i+1];const q=len?remaining/len:0;return{x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q}}remaining-=len}return path[path.length-1]}

function drawImage(key,x,y,w,h,alpha=1){const im=imgCache[key];if(!im||!im.complete||im.naturalWidth===0)return;ctx.save();ctx.globalAlpha=alpha;try{ctx.drawImage(im,x-w/2,y-h/2,w,h)}catch(e){}ctx.restore()}
function drawMap(){ctx.fillStyle='#2d7040';ctx.fillRect(0,0,W,H);const g=imgCache.ground;for(let y=0;y<H;y+=128)for(let x=0;x<W;x+=128)if(g.complete)ctx.drawImage(g,x,y,128,128);
// path shadow and path
ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#6b4a31';ctx.lineWidth=92;ctx.beginPath();ctx.moveTo(path[0].x,path[0].y);for(let p of path.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke();ctx.strokeStyle='#d8ad68';ctx.lineWidth=78;ctx.stroke();ctx.strokeStyle='#f3d98b';ctx.lineWidth=4;ctx.setLineDash([18,15]);ctx.stroke();ctx.restore();
// decoration
[[55,75,'tree',85,110],[1120,80,'tree',90,115],[70,630,'tree',75,100],[1125,620,'tree',80,105],[170,520,'bush',90,55],[880,600,'bush',95,60],[580,620,'rock',45,32],[1010,90,'rock',40,28],[104,470,'camp',60,60],[1110,540,'chest',70,55]].forEach(a=>drawImage(a[2],a[0],a[1],a[3],a[4],.9));
// base at end
 drawImage('base',1135,155,125,170,1);
 pads.forEach((p,i)=>{if(towers.some(t=>t.pad===i))return;ctx.save();ctx.strokeStyle='#ffe28a';ctx.setLineDash([8,7]);ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,52,25,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ffe28a';ctx.font='bold 23px system-ui';ctx.textAlign='center';ctx.fillText('+',p.x,p.y+8);ctx.restore()})}
function spawn(){if(spawnLeft<=0)return;const isBoss=wave%5===0&&spawnLeft===1;const type=isBoss?10:((wave+spawnLeft)%9)+1;const p=pathPoint(0);enemies.push({x:p.x,y:p.y,t:0,hp:isBoss?520+wave*40:55+wave*9,max:isBoss?520+wave*40:55+wave*9,speed:isBoss?38:78+Math.random()*22,kind:type,boss:isBoss,hit:0});spawnLeft--; if(isBoss){document.getElementById('bossbar').classList.remove('hidden');document.getElementById('bossName').textContent='FINAL BOSS';play('boss',.18)}}
function startWave(){if(running||wave>=20||gameEnded)return;wave++;spawnLeft=5+wave*2;spawnTimer=0;running=true;toast(wave%5===0?`BOSS WAVE ${wave}`:`WAVE ${wave}`);play('ui');setStats()}
function endRun(){if(gameEnded)return;finish(false)}
function finish(win){if(gameEnded)return;gameEnded=true;running=false;document.getElementById('resultTitle').textContent=win?'VICTORY':'GAME OVER';document.getElementById('resultWave').textContent=`${wave}/20`;document.getElementById('resultScore').textContent=score.toLocaleString();document.getElementById('resultStatus').textContent='Your score is ready to register.';document.getElementById('resultModal').classList.remove('hidden');play(win?'reward':'death',.35)}
function newGame(){towers=[];enemies=[];shots=[];fx=[];wave=0;lives=20;gold=300;score=0;running=false;selectedTower=null;gameEnded=false;document.getElementById('resultModal').classList.add('hidden');document.getElementById('panel').classList.add('hidden');document.getElementById('bossbar').classList.add('hidden');setStats();toast('NEW RUN READY')}
function place(type,i){const c=towerCfg[type];if(gold<c.cost){toast('Not enough gold');return false}if(towers.some(t=>t.pad===i))return false;gold-=c.cost;towers.push({type,pad:i,level:1,last:0,dmg:c.dmg,range:c.range,rate:c.rate,x:pads[i].x,y:pads[i].y});play('ui');setStats();return true}
function upgradeTower(t){const c=towerCfg[t.type],cost=Math.round(c.cost*.65*t.level);if(t.level>=5){toast('MAX LEVEL');return}if(gold<cost){toast(`Need $${cost}`);return}gold-=cost;t.level++;t.dmg=Math.round(c.dmg*(1+.42*(t.level-1)));t.range=c.range+14*(t.level-1);t.rate=Math.max(280,c.rate-65*(t.level-1));play('reward',.18);score+=25*t.level;setStats();updatePanel()}
function updatePanel(){if(!selectedTower)return;const t=selectedTower,c=towerCfg[t.type];document.getElementById('selType').textContent=t.type.toUpperCase();document.getElementById('selName').textContent=c.name;document.getElementById('selLevel').textContent=t.level;document.getElementById('selDamage').textContent=t.dmg;document.getElementById('selRange').textContent=Math.round(t.range);document.getElementById('selDesc').textContent=`Level ${t.level}/5 • Next upgrade changes the tower's power and attack stats.`;document.getElementById('upgrade').textContent=t.level>=5?'MAX LEVEL':`UPGRADE • $${Math.round(c.cost*.65*t.level)}`}
function fire(t,target,now){t.last=now;shots.push({x:t.x,y:t.y,target,dmg:t.dmg,type:t.type,life:0});play(t.type==='cannon'?'rocket':t.type==='mage'?'reward':'turret',.12)}
function update(dt,now){if(gameEnded)return;if(running){spawnTimer-=dt;if(spawnLeft>0&&spawnTimer<=0){spawn();spawnTimer=420}if(spawnLeft===0&&enemies.length===0){running=false;score+=100+wave*30;gold+=80+wave*5;play('reward',.18);if(wave>=20){finish(true);return}setStats();toast('WAVE CLEARED • +REWARD')}}
for(const e of enemies){if(e.hit>0)e.hit-=dt;if(!e.dead){e.t=Math.min(totalPath,e.t + e.speed*(dt/1000));}const p=pathPoint(Math.min(e.t,totalPath));e.x=p.x;e.y=p.y;if(e.t>=totalPath){e.dead=true;lives-=e.boss?5:1;score=Math.max(0,score-(e.boss?100:20));if(e.boss)document.getElementById('bossbar').classList.add('hidden');if(lives<=0){lives=0;setStats();finish(false);return}}}
for(const t of towers){let target=null,best=-1;for(const e of enemies){if(e.dead)continue;const d=dist(t,e);if(d<=t.range&&e.t>best){best=e.t;target=e}}if(target&&now-t.last>=t.rate)fire(t,target,now)}
for(const s of shots){s.life+=dt;if(!s.target||s.target.dead){s.life=999;continue}const dx=s.target.x-s.x,dy=s.target.y-s.y,d=Math.hypot(dx,dy),step=.85*dt;if(d<12){s.target.hp-=s.dmg;s.target.hit=90;score+=s.target.boss?20:5;fx.push({x:s.target.x,y:s.target.y,t:0});if(s.target.hp<=0){s.target.dead=true;gold+=s.target.boss?180:10;score+=s.target.boss?500:25;if(s.target.boss)document.getElementById('bossbar').classList.add('hidden');play('death',.12)}s.life=999}else{s.x+=dx/d*step;s.y+=dy/d*step}}
shots=shots.filter(s=>s.life<500);enemies=enemies.filter(e=>!e.dead);fx.forEach(f=>f.t+=dt);fx=fx.filter(f=>f.t<350);if(enemies.some(e=>e.boss)){const b=enemies.find(e=>e.boss);document.getElementById('bossHp').style.width=`${Math.max(0,b.hp/b.max*100)}%`;document.getElementById('bossHpText').textContent=`${Math.ceil(b.hp)} / ${b.max}`}setStats()}
function draw(now){drawMap();
// tower range selection and tower sprites
for(const t of towers){if(t===selectedTower){ctx.save();ctx.fillStyle='rgba(255,225,120,.09)';ctx.strokeStyle='rgba(255,225,120,.65)';ctx.setLineDash([8,8]);ctx.beginPath();ctx.arc(t.x,t.y,t.range,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}drawImage(t.type,t.x,t.y,t.type==='mage'?76:68,t.type==='mage'?126:88,1);ctx.fillStyle='#0a1519';ctx.beginPath();ctx.arc(t.x+25,t.y-35,14,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f8d76b';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 13px system-ui';ctx.textAlign='center';ctx.fillText(t.level,t.x+25,t.y-31)}
for(const e of enemies){const size=e.boss?115:62;const enemyKey=imgCache['e'+e.kind]&&imgCache['e'+e.kind].complete&&imgCache['e'+e.kind].naturalWidth?'e'+e.kind:'e3';drawImage(enemyKey,e.x,e.y,size*(e.boss?1.15:1),size*(e.boss?1.05:1),e.hit>0?.6:1);ctx.fillStyle='#162024';ctx.fillRect(e.x-size*.45,e.y-size*.65,size*.9,5);ctx.fillStyle=e.boss?'#ff4c55':'#55e38b';ctx.fillRect(e.x-size*.45,e.y-size*.65,size*.9*Math.max(0,e.hp/e.max),5)}
for(const s of shots){ctx.fillStyle=s.type==='mage'?'#83c8ff':s.type==='cannon'?'#ff9d59':'#ffe57c';ctx.beginPath();ctx.arc(s.x,s.y,s.type==='cannon'?7:5,0,Math.PI*2);ctx.fill()}
for(const f of fx){ctx.save();ctx.globalAlpha=1-f.t/350;ctx.strokeStyle='#fff2a8';ctx.lineWidth=4;ctx.beginPath();ctx.arc(f.x,f.y,10+f.t*.08,0,Math.PI*2);ctx.stroke();ctx.restore()}
}
let last=performance.now();function loop(now){const dt=Math.min(40,now-last);last=now;update(dt,now);draw(now);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function canvasPoint(ev){const r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left)*W/r.width,y:(ev.clientY-r.top)*H/r.height}}
canvas.addEventListener('pointerdown',e=>{const p=canvasPoint(e);for(let i=towers.length-1;i>=0;i--){if(dist(p,towers[i])<48){selectedTower=towers[i];updatePanel();document.getElementById('panel').classList.remove('hidden');return}}let best=-1,bd=70;pads.forEach((q,i)=>{const d=dist(p,q);if(d<bd&&!towers.some(t=>t.pad===i)){bd=d;best=i}});if(best>=0){place(selected,best)}});
document.querySelectorAll('.tower-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tower-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.type;toast(`Selected ${towerCfg[selected].name}`);play('ui')}));
document.getElementById('start').onclick=startWave;document.getElementById('end').onclick=endRun;document.getElementById('hero').onclick=()=>toast('Hero system: tap a deployed tower to upgrade. Hero deployment is next unlock.');document.getElementById('closePanel').onclick=()=>document.getElementById('panel').classList.add('hidden');document.getElementById('upgrade').onclick=()=>selectedTower&&upgradeTower(selectedTower);document.getElementById('sell').onclick=()=>{if(!selectedTower)return;gold+=Math.round(towerCfg[selectedTower.type].cost*.6*selectedTower.level);towers=towers.filter(t=>t!==selectedTower);selectedTower=null;document.getElementById('panel').classList.add('hidden');setStats();play('ui')};document.getElementById('submitResult').onclick=saveScore;document.getElementById('newRun').onclick=newGame;document.getElementById('refresh').onclick=loadScores;loadScores();setStats();
