import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getFirestore, collection, addDoc } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';

const CFG={
  firebase:{apiKey:'AIzaSyC2jNNzAkghmVE6KLOEgpDTd3CCTzpw3qo',authDomain:'leaderboard-90b9b.firebaseapp.com',projectId:'leaderboard-90b9b',storageBucket:'leaderboard-90b9b.firebasestorage.app',messagingSenderId:'891059392275',appId:'1:891059392275:web:757305992c2d83d39214e6'},
  path:[[-8,2.2],[-5,2.2],[-2,2.2],[1,2.2],[4,2.2],[4,-1],[1,-1],[-2,-1],[-5,-1],[-5,-4],[0,-4],[5,-4],[8,-4]],
  pads:[[-7,5],[-3,5],[1,5],[5,4],[-7,0],[-2,0],[2,0],[7,0],[-3,-6],[2,-6],[7,-1],[7,2]],
  towers:{turret:{cost:120,damage:14,range:4.1,rate:.75,weapon:'turret'},cannon:{cost:180,damage:32,range:4.7,rate:1.45,weapon:'cannon'},ballista:{cost:220,damage:45,range:5.2,rate:1.9,weapon:'ballista'},catapult:{cost:260,damage:62,range:5.6,rate:2.2,weapon:'catapult'}}
};
const firebaseApp=initializeApp(CFG.firebase); const db=getFirestore(firebaseApp);
const loader=new GLTFLoader(); const modelCache=new Map();
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x07121c); scene.fog=new THREE.Fog(0x07121c,28,58);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100); camera.position.set(0,18,19); camera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.7)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; document.getElementById('game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xaad7ff,0x16220f,1.7)); const sun=new THREE.DirectionalLight(0xffffff,2.2); sun.position.set(-10,22,12); sun.castShadow=true; sun.shadow.mapSize.set(1024,1024); scene.add(sun);
const world=new THREE.Group(); scene.add(world); const pathGroup=new THREE.Group(); world.add(pathGroup); const padsGroup=new THREE.Group(); world.add(padsGroup); const unitsGroup=new THREE.Group(); world.add(unitsGroup);
const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2(); const groundPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
let state={wave:1,hp:20,gold:600,score:0,combo:0,bestCombo:0,paused:false,gameOver:false,won:false,submitted:false,start:Date.now(),rushUntil:0,rushMult:1,spawned:0,total:0,enemies:[],towers:[],selectedTower:null,selectedHero:false,hero:null};
let pads=[]; let ghost=null; let dragType=null; let dragPointerId=null;
const $=id=>document.getElementById(id); const fmt=n=>Math.floor(n).toLocaleString();
function toast(t,d=1800){const m=$('message');m.textContent=t;clearTimeout(m._t);m._t=setTimeout(()=>m.textContent='',d)}
function updateHud(){ $('wave').textContent=state.wave; $('hp').textContent=state.hp; $('gold').textContent=fmt(state.gold); $('score').textContent=fmt(state.score); const active=state.rushUntil>Date.now(); $('rush').hidden=!active; if(active){$('rushTime').textContent=Math.max(0,Math.ceil((state.rushUntil-Date.now())/1000));$('rushMult').textContent='×'+state.rushMult} }
function loadModel(path){if(modelCache.has(path)) return modelCache.get(path); const p=new Promise((res,rej)=>loader.load(path,g=>res(g.scene),undefined,rej)); modelCache.set(path,p); return p;}
function fit(obj,size=1.4){const b=new THREE.Box3().setFromObject(obj); const s=new THREE.Vector3();b.getSize(s); const m=Math.max(s.x,s.y,s.z)||1; obj.scale.multiplyScalar(size/m); obj.position.y += (b.min.y*-obj.scale.y)+0.02; return obj;}
async function addAsset(parent,path,pos,size=1){try{const base=await loadModel(path);const obj=base.clone(true); fit(obj,size); obj.position.set(pos[0],0,pos[1]); obj.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});parent.add(obj);return obj}catch(e){console.warn('Asset load failed',path,e);return null}}
function box(w,h,d,color,y=.0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.8}));m.position.y=y;m.castShadow=true;m.receiveShadow=true;return m}
function setupTerrain(){
  const ground=box(30,.45,20,0x274a39,-.28); world.add(ground);
  for(let x=-9;x<=9;x+=3){for(let z=-6;z<=6;z+=3){const tile=box(2.82,.08,2.82,0x35634a,-.02);tile.position.set(x,0,z);world.add(tile)}}
  const pathMat=new THREE.MeshStandardMaterial({color:0x6b563e,roughness:1});
  CFG.path.forEach(([x,z],i)=>{const p=box(2.7,.12,2.7,0x6b563e,.03);p.position.set(x,0,z);pathGroup.add(p);});
  CFG.path.forEach(([x,z],i)=>{if(i%2===0) addAsset(world,'assets/terrain/tile.glb',[x,0,z],2.75).catch(()=>{})});
  CFG.pads.forEach(([x,z],i)=>{const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.CylinderGeometry(.72,.72,.08,32),new THREE.MeshStandardMaterial({color:0x4dbb8b,emissive:0x164a35,transparent:true,opacity:.9}));ring.position.y=.1;g.add(ring);const inner=new THREE.Mesh(new THREE.CylinderGeometry(.58,.58,.06,32),new THREE.MeshStandardMaterial({color:0x122d2b,transparent:true,opacity:.8}));inner.position.y=.15;g.add(inner);g.position.set(x,0,z);padsGroup.add(g);pads.push({x,z,group:g,tower:null,available:true});});
}
function createHero(){const g=new THREE.Group();g.position.set(0,.2,6.2);g.userData.type='hero';
  const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1.0,6,10),new THREE.MeshStandardMaterial({color:0x6d5bff,metalness:.2,roughness:.65}));body.position.y=.9;body.castShadow=true;g.add(body);
  const head=new THREE.Mesh(new THREE.SphereGeometry(.34,16,12),new THREE.MeshStandardMaterial({color:0xffc39c,roughness:.8}));head.position.y=1.75;head.castShadow=true;g.add(head);
  const cape=new THREE.Mesh(new THREE.ConeGeometry(.55,.9,5,1,true),new THREE.MeshStandardMaterial({color:0x151d39,side:THREE.DoubleSide,roughness:.9}));cape.position.set(0,1.0,.25);cape.rotation.x=Math.PI;g.add(cape);
  const ring=new THREE.Mesh(new THREE.TorusGeometry(.55,.035,8,24),new THREE.MeshBasicMaterial({color:0x7ee7ff}));ring.rotation.x=Math.PI/2;ring.position.y=.08;g.add(ring);
  g.userData.level=1;g.userData.damage=35;g.userData.range=3.5;g.userData.rate=.65;g.userData.last=0;unitsGroup.add(g);state.hero=g;return g;}
function buildTowerVisual(t){const group=new THREE.Group(); const base='assets/towers/'; const parts=['tower-round-base.glb','tower-round-bottom-a.glb','tower-round-middle-a.glb','tower-round-roof-a.glb','tower-round-top-a.glb'];
  Promise.all(parts.map(p=>loadModel(base+p))).then(models=>{models.forEach((m,i)=>{const o=m.clone(true);fit(o,1.25+i*.08);o.position.y=i*.32;group.add(o);}); const weapon=state.towers.find(x=>x===t)?t.userData.weapon:'turret'; loadModel('assets/weapons/weapon-'+weapon+'.glb').then(m=>{const o=m.clone(true);fit(o,.95+t.userData.level*.06);o.position.y=1.65;group.add(o);t.userData.weaponObj=o;}).catch(()=>{}); if(t.userData.level>=3){const r=new THREE.Mesh(new THREE.TorusGeometry(.75,.045,8,32),new THREE.MeshBasicMaterial({color:0x6ff3ff,emissive:0x6ff3ff}));r.rotation.x=Math.PI/2;r.position.y=2.15;group.add(r)} }).catch(()=>{}); return group;}
function spawnTower(type,pad){const d=CFG.towers[type]; if(state.gold<d.cost){toast('Not enough gold');return null} state.gold-=d.cost;pad.available=false;const t=new THREE.Group();t.position.set(pad.x,0,pad.z);t.userData={type,level:1,damage:d.damage,range:d.range,rate:d.rate,last:0,weapon:d.weapon,pad};t.add(buildTowerVisual(t));t.traverse(o=>{if(o.isMesh)o.castShadow=true});unitsGroup.add(t);state.towers.push(t);pad.tower=t;updateHud();return t}
function upgradeTower(t){const max=5;if(t.userData.level>=max){toast('MAX LEVEL');return}const cost=Math.round(CFG.towers[t.userData.type].cost*(.75+t.userData.level*.6));if(state.gold<cost){toast('Need '+cost+' gold');return}state.gold-=cost;t.userData.level++;t.userData.damage=Math.round(t.userData.damage*1.55);t.userData.range+=.42;t.userData.rate*=.91;const old=t.children[0];if(old) t.remove(old);t.add(buildTowerVisual(t));toast('Tower upgraded to Lv '+t.userData.level);selectTower(t);updateHud()}
function sellTower(t){const refund=Math.round(CFG.towers[t.userData.type].cost*(.55+t.userData.level*.12));state.gold+=refund;t.userData.pad.available=true;t.userData.pad.tower=null;unitsGroup.remove(t);state.towers=state.towers.filter(x=>x!==t);hidePanels();updateHud()}
function selectTower(t){state.selectedTower=t;state.selectedHero=false;$('towerPanel').classList.remove('hidden');$('heroPanel').classList.add('hidden');$('towerTitle').textContent=t.userData.type.toUpperCase()+' • LV '+t.userData.level;const cost=Math.round(CFG.towers[t.userData.type].cost*(.75+t.userData.level*.6));$('towerStats').innerHTML=`<div>Damage<br><b>${fmt(t.userData.damage)}</b></div><div>Range<br><b>${t.userData.range.toFixed(1)}</b></div><div>Attack<br><b>${t.userData.rate.toFixed(2)}s</b></div><div>Upgrade<br><b>${t.userData.level>=5?'MAX':'💰 '+cost}</b></div>`;$('upgradeBtn').classList.toggle('disabled',t.userData.level>=5||state.gold<cost)}
function selectHero(){state.selectedHero=true;state.selectedTower=null;$('heroPanel').classList.remove('hidden');$('towerPanel').classList.add('hidden');const h=state.hero;$('heroStats').innerHTML=`<div class="heroStats">Level <b>${h.userData.level}</b><br>Damage <b>${fmt(h.userData.damage)}</b><br>Range <b>${h.userData.range.toFixed(1)}</b></div>`;$('heroUpgradeBtn').classList.toggle('disabled',h.userData.level>=10||state.gold<Math.round(250*h.userData.level))}
function upgradeHero(){const h=state.hero;if(h.userData.level>=10){toast('HERO MAX');return}const cost=250*h.userData.level;if(state.gold<cost){toast('Need '+cost+' gold');return}state.gold-=cost;h.userData.level++;h.userData.damage=Math.round(h.userData.damage*1.35);h.userData.range+=.25;h.scale.multiplyScalar(1.04);h.children[0].material.color.setHex([0x6d5bff,0x5bbdff,0x6ff3c1,0xffc857,0xff7a6f,0xff4fd8,0xb58cff,0xfff28a,0xffffff,0xff4f4f][Math.min(9,h.userData.level-1)]);toast('HERO LEVEL '+h.userData.level);selectHero();updateHud()}
function hidePanels(){ $('towerPanel').classList.add('hidden');$('heroPanel').classList.add('hidden');state.selectedTower=null;state.selectedHero=false }
function updatePadHighlights(active){pads.forEach(p=>{if(!p.available)return; p.group.visible=active;});}
function worldPoint(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);const v=new THREE.Vector3();return raycaster.ray.intersectPlane(groundPlane,v)?v:null}
function nearestPad(v){let best=null,dist=Infinity;for(const p of pads){if(!p.available)continue;const d=Math.hypot(v.x-p.x,v.z-p.z);if(d<1.05&&d<dist){best=p;dist=d}}return best}
function pointerDown(e){if(state.gameOver||state.paused)return;const v=worldPoint(e); if(!v)return; const hits=raycaster.intersectObjects(unitsGroup.children,true); const hit=hits[0]?.object; let root=hit;while(root&&root.parent!==unitsGroup)root=root.parent;if(root?.userData?.type==='hero'){dragType='hero';dragPointerId=e.pointerId;selectHero();return}if(root?.userData?.pad){selectTower(root);return}}
function pointerMove(e){if(dragType==='hero'&&e.pointerId===dragPointerId){const v=worldPoint(e);if(v){state.hero.position.x=THREE.MathUtils.clamp(v.x,-9,9);state.hero.position.z=THREE.MathUtils.clamp(v.z,-6.5,6.5)}} if(ghost&&e.pointerId===dragPointerId){const v=worldPoint(e);if(v){ghost.position.set(v.x,.2,v.z);const p=nearestPad(v);ghost.userData.pad=p;ghost.children[0].material.color.setHex(p?0x62e6a5:0xff5b65)}}}
function pointerUp(e){if(e.pointerId!==dragPointerId)return;if(dragType==='hero'){dragType=null;dragPointerId=null;return}if(ghost){const p=ghost.userData.pad;if(p)spawnTower(dragType,p);scene.remove(ghost);ghost=null;updatePadHighlights(false)}dragType=null;dragPointerId=null}
function startDragCard(type,e){if(state.gameOver||state.paused)return;e.preventDefault();if(e.currentTarget?.setPointerCapture){try{e.currentTarget.setPointerCapture(e.pointerId)}catch{}}dragType=type;dragPointerId=e.pointerId;const g=new THREE.Group();const m=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,.22,24),new THREE.MeshStandardMaterial({color:0x62e6a5,transparent:true,opacity:.75}));g.add(m);g.userData.pad=null;scene.add(g);ghost=g;updatePadHighlights(true);const v=worldPoint(e);if(v)g.position.set(v.x,.2,v.z)}
function makeEnemy(type,boss=false){const g=new THREE.Group();g.userData={type:'enemy',boss,health:boss?260+state.wave*80:55+state.wave*15,maxHealth:boss?260+state.wave*80:55+state.wave*15,speed:boss?.85:1.35+(type*.08),pathIndex:0,progress:0,reward:boss?350+state.wave*50:25+state.wave*4,lastHit:0};const file=['enemy-ufo-a.glb','enemy-ufo-b.glb','enemy-ufo-c.glb','enemy-ufo-d.glb'][type%4];loadModel('assets/enemies/'+file).then(m=>{const o=m.clone(true);fit(o,boss?2.0:1.05);o.position.y=.55;g.add(o);}).catch(()=>{const o=new THREE.Mesh(new THREE.SphereGeometry(boss?.8:.4,16,12),new THREE.MeshStandardMaterial({color:boss?0xff4e59:0x9a8cff,emissive:boss?0x3a0710:0x140a33}));o.position.y=.5;g.add(o)});g.position.set(CFG.path[0][0],0,CFG.path[0][1]);unitsGroup.add(g);state.enemies.push(g);return g}
function spawnWave(){state.spawned=0;state.total=6+state.wave;const count=state.total;let i=0;const iv=setInterval(()=>{if(state.gameOver||state.paused){return}if(i>=count){clearInterval(iv);const boss=makeEnemy((state.wave+1)%4,true);boss.position.set(CFG.path[0][0]-1.5,0,CFG.path[0][1]);state.spawned++;return}makeEnemy(i%4,false);i++},420)}
function damageEnemy(e,amount){e.userData.health-=amount;state.score+=Math.round(amount*(state.rushUntil>Date.now()?state.rushMult:1));if(e.userData.health<=0){killEnemy(e)}}
function killEnemy(e){const mult=state.rushUntil>Date.now()?state.rushMult:1;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);state.score+=Math.round(e.userData.reward*mult*(1+Math.min(state.combo,10)*.03));state.gold+=e.userData.reward;unitsGroup.remove(e);state.enemies=state.enemies.filter(x=>x!==e);if(e.userData.boss){toast('👑 BOSS DEFEATED +'+e.userData.reward);state.score+=1000*state.wave}else if(state.combo%5===0)toast('🔥 COMBO ×'+Math.min(5,1+Math.floor(state.combo/5)));updateHud()}
function moveEnemies(dt){for(const e of [...state.enemies]){if(!e.parent)continue;const idx=e.userData.pathIndex;const target=CFG.path[Math.min(idx+1,CFG.path.length-1)];const dx=target[0]-e.position.x,dz=target[1]-e.position.z;const len=Math.hypot(dx,dz);if(len<.12){if(idx>=CFG.path.length-2){state.hp-=e.userData.boss?5:1;state.combo=0;unitsGroup.remove(e);state.enemies=state.enemies.filter(x=>x!==e);if(state.hp<=0)endRun(false);continue}e.userData.pathIndex++;continue}e.position.x+=dx/len*e.userData.speed*dt;e.position.z+=dz/len*e.userData.speed*dt;e.rotation.y=Math.atan2(dx,dz)}}
function towerAttack(t,now){let target=null,best=Infinity;for(const e of state.enemies){const d=t.position.distanceTo(e.position);if(d<=t.userData.range&&d<best){best=d;target=e}}if(target&&now-t.userData.last>=t.userData.rate*1000){t.userData.last=now;damageEnemy(target,t.userData.damage);const shot=new THREE.Mesh(new THREE.SphereGeometry(.1,8,8),new THREE.MeshBasicMaterial({color:0xffdc68}));shot.position.copy(t.position);world.add(shot);const start=shot.position.clone(),end=target.position.clone();let p=0;const anim=()=>{p+=.18;shot.position.lerpVectors(start,end,p);if(p<1&&shot.parent)requestAnimationFrame(anim);else world.remove(shot)};anim()}}
function heroAttack(now){const h=state.hero;if(!h||now-h.userData.last<h.userData.rate*1000)return;let target=null,best=Infinity;for(const e of state.enemies){const d=h.position.distanceTo(e.position);if(d<=h.userData.range&&d<best){best=d;target=e}}if(target){h.userData.last=now;damageEnemy(target,h.userData.damage)}}
function beginRush(){state.rushUntil=Date.now()+60000;state.rushMult=2+Math.min(2,Math.floor(state.wave/6));toast('⚡ BATTLE RUSH ×'+state.rushMult+' — 60s',2400);updateHud()}
function nextWave(){if(state.gameOver)return;state.wave++;state.gold+=100+state.wave*12;if(state.wave%3===0)beginRush();if(state.wave>20){endRun(true);return}toast('WAVE '+state.wave+' — BOSS INCOMING',1800);spawnWave();updateHud()}
function checkWave(){if(state.enemies.length===0&&state.spawned>=state.total+1){if(state.wave>=20)endRun(true);else setTimeout(nextWave,1300)}}
async function submitScore(){if(state.submitted)return true;state.submitted=true;const name=localStorage.getItem('irwflixPlayerName')||prompt('Enter your player name')||'Player';localStorage.setItem('irwflixPlayerName',name);const payload={game:'defense',name,score:Math.floor(state.score),wave:state.wave,timeSeconds:Math.floor((Date.now()-state.start)/1000),bestCombo:state.bestCombo,createdAt:Date.now()};try{await Promise.race([addDoc(collection(db,'leaderboard'),payload),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),7000))]);toast('🏆 SCORE REGISTERED',2200);return true}catch(e){console.error(e);state.submitted=false;toast('Score could not reach Firebase',2600);return false}}
function endRun(win){if(state.gameOver)return;state.gameOver=true;state.won=win;state.paused=false;$('modalTitle').textContent=win?'🏆 VICTORY':'💀 GAME OVER';$('modalBody').innerHTML=`<p>Wave <b>${state.wave}</b></p><p>Score <b>${fmt(state.score)}</b></p><p>Best Combo <b>×${Math.max(1,Math.min(9,1+Math.floor(state.bestCombo/5)))}</b></p>`;$('modal').classList.remove('hidden');submitScore();}
function reset(){location.reload()}
$('upgradeBtn').onclick=()=>state.selectedTower&&upgradeTower(state.selectedTower);$('sellBtn').onclick=()=>state.selectedTower&&sellTower(state.selectedTower);$('closeTower').onclick=hidePanels;$('closeHero').onclick=hidePanels;$('heroBtn').onclick=selectHero;$('heroUpgradeBtn').onclick=upgradeHero;$('pauseBtn').onclick=()=>{state.paused=!state.paused;$('pauseBtn').textContent=state.paused?'▶ RESUME':'Ⅱ PAUSE';toast(state.paused?'PAUSED':'RESUMED')};$('endBtn').onclick=()=>endRun(false);$('submitBtn').onclick=submitScore;$('restartBtn').onclick=reset;
document.querySelectorAll('.towerCard').forEach(c=>{c.addEventListener('pointerdown',e=>startDragCard(c.dataset.type,e));});renderer.domElement.addEventListener('pointerdown',pointerDown);document.addEventListener('pointermove',pointerMove,{passive:false});document.addEventListener('pointerup',pointerUp,{passive:false});document.addEventListener('pointercancel',pointerUp,{passive:false});
setupTerrain();createHero();updatePadHighlights(false);spawnWave();updateHud();
let last=performance.now();function loop(now){requestAnimationFrame(loop);const dt=Math.min(.05,(now-last)/1000);last=now;if(!state.paused&&!state.gameOver){moveEnemies(dt);const n=Date.now();state.towers.forEach(t=>towerAttack(t,n));heroAttack(n);if(state.rushUntil&&state.rushUntil<Date.now()){state.rushUntil=0;state.rushMult=1;toast('Battle Rush ended — normal scoring',1500)}checkWave();updateHud()}renderer.render(scene,camera)}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7))});
